WebAppGraficosHighcharts/Models/Avaliacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppGraficosHighcharts.Models
{
    public class Avaliacao
    {
        public int Id { get; set; }
        public int Pessimo { get; set; }
        public int Ruim { get; set; }
        public int Indiferente { get; set; }
        public int Bom { get; set; }
        public int Otimo { get; set; }
    }
}

WebAppGraficosHighcharts/Models/Enum/ETipoConsulta.cs
using System.ComponentModel.DataAnnotations;

namespace WebAppGraficosHighcharts.Models.Enum
{
    public enum ETipoConsulta
    {
        [Display(Name = "Relação por Empresa")]
        Empresa = 1,

        [Display(Name = "Relação por Cargo")]
        Cargo = 2,

        [Display(Name = "Relação por Contrato")]
        Contrato = 3
    }
}

WebAppGraficosHighcharts/Models/ErrorViewModel.cs
using System;

namespace WebAppGraficosHighcharts.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAppGraficosHighcharts/Models/Populacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppGraficosHighcharts.Models
{
    public class Populacao
    {
        public string Cidade { get; set; }
        public decimal Populacao2017 { get; set; }
        public decimal Populacao2010 { get; set; }
    }
}

WebAppGraficosHighcharts/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebAppGraficosHighcharts.Controllers
{
    public class ClienteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebAppGraficosHighcharts/Controllers/FuncionarioController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using WebAppGraficosHighcharts.Factory;
using WebAppGraficosHighcharts.Models.Enum;
using WebAppGraficosHighcharts.Services;
using WebAppGraficosHighcharts.ViewModel;

namespace WebAppGraficosHighcharts.Controllers
{
    public class FuncionarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Filtrar(FiltroFuncionarioViewModel filtroVM)
        {
            var tabela = new TabelaFuncionarioViewModel();
            if (filtroVM.TipoDeConsulta == ETipoConsulta.Empresa)
            {
                var lista = FuncionarioEmpresaService.BuscarEmpresas();
                tabela.FuncionariosEmpresa = FuncionarioFactory.ListaFuncionariosPorEmpresa(lista);
            }
            else if (filtroVM.TipoDeConsulta == ETipoConsulta.Cargo)
            {
                var lista = FuncionarioCargoService.BuscarCargos();
                tabela.FuncionariosCargo = FuncionarioFactory.ListaFuncionariosPorCargo(lista);
            }
            else
            {
                var lista = FuncionarioContratoService.BuscarContratos();
                tabela.FuncionariosContrato = FuncionarioFactory.ListaFuncionariosPorContrato(lista);
            }
            return PartialView("Partials/_TabelaFuncionarios", tabela);
        }
    }
}

WebAppGraficosHighcharts/Controllers/HomeController.cs
using DotNet.Highcharts;
using DotNet.Highcharts.Enums;
using DotNet.Highcharts.Helpers;
using DotNet.Highcharts.Options;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using WebAppGraficosHighcharts.Models;
using WebAppGraficosHighcharts.Services;

namespace WebAppGraficosHighcharts.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Index2()
        {
            return View();
        }

        public JsonResult BuscarAvaliacoes()
        {
            var listaAvaliacao = AvaliacaoService.BuscarAvaliacoes();
            return Json(listaAvaliacao);
        }

        public IActionResult Index3()
        {
            return View();
        }

        public JsonResult BuscarCidadesPopulosas()
        {
            var listaDePopulacao = PopulacaoService.GetPopulacaoPorEstado();
            return Json(listaDePopulacao);
        }

        public IActionResult Index4()
        {
            var listaAvaliacao = AvaliacaoService.BuscarAvaliacoes();

            var lista = new List<Avaliacao>();
            int totalPessimo = 0, totalRuim = 0, totalIndiferente = 0, totalBom = 0, totalOtimo = 0;

            listaAvaliacao.ForEach(x =>
            {
                totalPessimo += x.Pessimo;
                totalRuim += x.Ruim; totalIndiferente += x.Indiferente;
                totalBom += x.Bom; totalOtimo += x.Otimo;
            });

            var pessimo = totalPessimo;
            var ruim = totalRuim;
            var indiferente = totalIndiferente;
            var bom = totalBom;
            var otimo = totalOtimo;

            lista.Add(new Avaliacao { Pessimo = pessimo, Ruim = ruim, Indiferente = indiferente, Bom = bom, Otimo = otimo });

            return View(lista);
        }

        //public JsonResult BuscarResultadosAvaliacao()
        //{
        //    var listaAvaliacao = AvaliacaoService.BuscarAvaliacoes();
        //    return Json(listaAvaliacao);
        //}




        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        public IActionResult Avaliacao()
        {
            Highcharts columnChart = new Highcharts("columnchart");
            columnChart.InitChart(new Chart()
            {
                Type = DotNet.Highcharts.Enums.ChartTypes.Column,
                BackgroundColor = new BackColorOrGradient(System.Drawing.Color.AliceBlue),
                Style = "fontWeight: 'bold', fontSize: '17px'",
                BorderColor = System.Drawing.Color.LightBlue,
                BorderRadius = 0,
                BorderWidth = 2
            });
            columnChart.SetTitle(new Title()
            {
                Text = "Santos x São Paulo"
            });
            columnChart.SetSubtitle(new Subtitle()
            {
                Text = "Classificação por pontos no Campeonato Brasileiro"
            });
            columnChart.SetXAxis(new XAxis()
            {
                Type = AxisTypes.Category,
                Title = new XAxisTitle() { Text = "Anos", Style = "fontWeight: 'bold', fontSize: '17px'" },
                Categories = new[] { "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012" }
            });
            columnChart.SetYAxis(new YAxis()
            {
                Title = new YAxisTitle()
                {
                    Text = "Pontos",
                    Style = "fontWeight: 'bold', fontSize: '17px'"
                },
                ShowFirstLabel = true,
                ShowLastLabel = true,
                Min = 0
            });
            columnChart.SetLegend(new Legend
            {
                Enabled = true,
                BorderColor = System.Drawing.Color.CornflowerBlue,
                BorderRadius = 6,
                BackgroundColor = new BackColorOrGradient(ColorTranslator.FromHtml("#FFADD8E6"))
            });
            columnChart.SetSeries(new Series[]
            {
                new Series{
                    Name = "Santos",
                    Data = new Data(new object[] { 89, 59, 64, 62, 45, 49, 53, 53, 57 })
                },
                new Series()
                {
                    Name = "São Paulo",
                    Data = new Data(new object[] { 82, 58, 78, 77, 75, 65, 59, 66, 50 })
                }
            }
            );
            return View(columnChart);
        }
    }
}

WebAppGraficosHighcharts/Views/Cliente/Index.cshtml
@section Head{
    <link href="~/css/Cliente/paginacao.css" rel="stylesheet" />
}

<figure class="highcharts-figure">
    <div id="grafico-funcionarios"></div>
    <p class="highcharts-description">
        Chart showing how an HTML table can be used as the data source for the
        chart using the Highcharts data module. The chart is built by
        referencing the existing HTML data table in the page. Several common
        data source types are available, including CSV and Google Spreadsheet.
    </p>

    <table id="tabela-funcionarios">
        <thead>
            <tr>
                <th></th>
                <th>Boys</th>
                <th>Girls</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                @*<th>2016</th>*@
                <td>30 386</td>
                <td>28 504</td>
            </tr>
            <tr>
                @*<th>2017</th>*@
                <td>29 173</td>
                <td>27 460</td>
            </tr>
            <tr>
                @*<th>2018</th>*@
                <td>28 430</td>
                <td>26 690</td>
            </tr>
            <tr>
                @*<th>2019</th>*@
                <td>28 042</td>
                <td>26 453</td>
            </tr>
            <tr>
                @*<th>2020</th>*@
                <td>27 063</td>
                <td>25 916</td>
            </tr>
            <tr>
                @*<th>2021</th>*@
                <td>28 684</td>
                <td>27 376</td>
            </tr>
        </tbody>
    </table>
</figure>

@section Scripts{
    <script src="~/js/cliente/grafico.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/data.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
}

WebAppGraficosHighcharts/Views/Funcionario/Index.cshtml
@model WebAppGraficosHighcharts.ViewModel.IndexFuncionarioViewModel

@{
    ViewData["Title"] = "Paginação de Funcionários";
}

@section Head{
    <partial name="Css\_datatables" />
    <partial name="Css\_bootstrap-select" />
}

<div class="container">
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb mb-0 pl-0">
            <li class="breadcrumb-item active" aria-current="page">@ViewData["Title"]</li>
        </ol>
    </nav>
</div>

<div class="container">
    <div class="card mt-0">
        <div class="card-body">
            <div class="row">
                <div class="col-12 text-center">
                    <h3 class="title">@ViewData["Title"]</h3>
                </div>

                <div class="col-12">
                    <partial name="Partials\_FiltroFuncionarios" />
                </div>

                <div class="col-12">
                    <div id="grafico-funcionarios" style="width:100%; height:100%;"></div>
                </div>

                <div class="col-12" id="tabela-partial">
                    <partial name="Partials\_TabelaFuncionarios" />
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <partial name="Script\_datatables" />
    <partial name="Script\_highCharts" />
    <partial name="Script\_bootstrap-select" />

    <script src="~/js/filtroFuncionarios.js"></script>
    <script src="~/js/grafico.js"></script>
}

WebAppGraficosHighcharts/Views/Funcionario/Partials/_FiltroFuncionarios.cshtml
@model WebAppGraficosHighcharts.ViewModel.FiltroFuncionarioViewModel
@using WebAppGraficosHighcharts.Models.Enum

<form asp-controller="Funcionario" asp-action="Filtrar" id="form-filtro-funcionarios" autocomplete="off">
    <div class="form-row">

        <div class="form-group col-lg-2 col-sm-12">
            <select asp-items="Html.GetEnumSelectList<ETipoConsulta>()" asp-for="TipoDeConsulta" class="form-control selectpicker"></select>
        </div>

        <div class="form-group col-sm-12 text-center">
            <button type="submit" class="btn btn-primary btn-round col-md-6">
                <i class="fa fa-filter" aria-hidden="true"></i> Filtrar
            </button>
        </div>
    </div>
</form>

WebAppGraficosHighcharts/Views/Funcionario/Partials/_TabelaFuncionarios.cshtml
@model WebAppGraficosHighcharts.ViewModel.TabelaFuncionarioViewModel

@if (Model != null)
{
    <table id="tabela-funcionarios" class="table table-hover table-light" style="width: 100%; " data-order="[]">
        <thead style="width: 100%; white-space:nowrap">
            <tr>
                @if (Model.FuncionariosEmpresa.Any())
                {
                    <th>Empresas</th>
                    <th class="text-center">Qtd Funcionários</th>
                }
                else if (Model.FuncionariosCargo.Any())
                {
                    <th>Cargos</th>
                    <th class="text-center">Qtd Funcionários</th>
                }

                else
                {
                    <th>Contratos</th>
                    <th class="text-center">Qtd Funcionários</th>
                }
            </tr>
        </thead>
        <tbody>
            @if (Model.FuncionariosEmpresa.Any())
            {
                @foreach (var funcionario in Model.FuncionariosEmpresa)
                {
                    <tr>
                        <td>@funcionario.Empresa</td>
                        <td class="text-center">@funcionario.QtdFuncionarios</td>
                    </tr>
                } }

            else if (Model.FuncionariosCargo.Any())
            {
                @foreach (var funcionario in Model.FuncionariosCargo)
                {
                    <tr>
                        <td>@funcionario.Cargo</td>
                        <td class="text-center">@funcionario.QtdFuncionarios</td>
                    </tr>
                } }

            else
            {
                @foreach (var funcionario in Model.FuncionariosContrato)
                {
                    <tr>
                        <td>@funcionario.Contrato</td>
                        <td class="text-center">@funcionario.QtdFuncionarios</td>
                    </tr>
                }}
        </tbody>
    </table>
}
else
{
    <div>Nenhum registro encontrado</div>
}

WebAppGraficosHighcharts/Views/Home/Avaliacao.cshtml
<p>teste</p>

WebAppGraficosHighcharts/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<html>
<head>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script>
        google.charts.load('current', { packages: ['corechart'] });
        function desenharGrafico() {
            var tabela = new google.visualization.DataTable();
            tabela.addColumn('string', 'avaliacao');
            tabela.addColumn('number', 'resultado');
            tabela.addRows(
                [
                    ['Péssimo', 50],
                    ['Ruim', 70],
                    ['Indiferente', 20],
                    ['Bom', 100],
                    ['Ótimo', 250]
                ]);

            var opcoes = {
                'title': 'Resultado Avaliação',
                'hight': 300,
                'width': 800,
                is3D: true,
                legend: 'labeled',
                pieSliceText: 'value',
                //colors: ['red', 'yellow', 'purple', 'blue', 'green']
                slices: {
                    0: { color: 'red' },
                    1: { color: 'grey' },
                    2: { color: 'purple' },
                    3: { color: 'blue' },
                    4: { offset: 0.2, color: 'green' },
                }
            };
            var grafico = new google.visualization.PieChart(document.getElementById('graficoPizza'));
            grafico.draw(tabela, opcoes);
        }

        google.charts.setOnLoadCallback(desenharGrafico);

    </script>

</head>
<body>
    <div id="graficoPizza"></div>
</body>
</html>

WebAppGraficosHighcharts/Views/Home/Index2.cshtml
@{
    ViewData["Title"] = "Index2";
}

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div id="chart_div" style="width: 900px; height: 500px;"></div>
<script type="text/javascript">

    google.charts.load('current', {packages: ['corechart', 'bar']});
    google.charts.setOnLoadCallback(CarregaDados);
    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("BuscarAvaliacoes", "Home")',
            dataType: "json",
            type: "GET",
            error: function(xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function(data) {
                GraficoAvaliacao(data);
                return false;
            }
        });
        return false;
    }
    function GraficoAvaliacao(data) {
        var dataArray = [
            ['Pessimo', 'Ruim' , 'Indiferente', 'Bom', 'Otimo']
        ];
        $.each(data, function(i, item) {
            dataArray.push([item.pessimo, item.ruim, item.indiferente, item.bom, item.otimo]);
        });
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Avaliação do Portal',
            chartArea: {
                width: '50%'
            },
            colors: ['#b0120a', '#ffab91'],
            hAxis: {
                title: 'Avaliação do Portal de Cursos Online',
                minValue: 0
            },
            vAxis: {
                title: 'Pessimo'
            }
        };
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
        return false;
    }
</script>

WebAppGraficosHighcharts/Views/Home/Index3.cshtml
@{
    ViewData["Title"] = "Index3";
}

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<div id="chart_div" style="width: 900px; height: 500px;"></div>
<script type="text/javascript">

    google.charts.load('current', {packages: ['corechart', 'bar']});
    google.charts.setOnLoadCallback(CarregaDados);
    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("BuscarCidadesPopulosas", "Home")',
            dataType: "json",
            type: "GET",
            error: function(xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function(data) {
                GraficoPopulacional(data);
                return false;
            }
        });
        return false;
    }
    function GraficoPopulacional(data) {
        var dataArray = [
            ['Cidade', '2010' , '2017']
        ];
        $.each(data, function(i, item) {
            dataArray.push([item.cidade, item.populacao2010, item.populacao2017]);
        });
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Brasil - População das 5 Cidades mais populosas',
            chartArea: {
                width: '50%'
            },
            colors: ['#b0120a', '#ffab91'],
            hAxis: {
                title: 'Populacao Total (em milhões)',
                minValue: 0
            },
            vAxis: {
                title: 'Cidade'
            }
        };
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
        return false;
    }
</script>

WebAppGraficosHighcharts/Views/Home/Index4.cshtml
@model IEnumerable<WebAppGraficosHighcharts.Models.Avaliacao>
@{
    ViewData["Title"] = "Index4";
}

<div style="overflow-x:auto;">
    <table class="table table-striped table-responsive">
        <tr>
            <th>Péssimo</th>
            <th>Ruim</th>
            <th>Indiferente</th>
            <th>Bom</th>
            <th>Ótimo</th>
        </tr>
        <tr>
            @foreach (var item in Model)
            {
                <td><p id="pessimo">@item.Pessimo</p></td>
                <td><p id="ruim">@item.Ruim</p></td>
                <td><p id="indiferente">@item.Indiferente</p></td>
                <td><p id="bom">@item.Bom</p></td>
                <td><p id="otimo">@item.Otimo</p></td>
            }
        </tr>
    </table>
</div>

<html>
<head>
    <script>
        const pessimo = document.getElementById("pessimo").innerHTML;
        let ruim = document.getElementById("ruim").innerHTML;
        let indiferente = document.getElementById("indiferente").innerHTML;
        let bom = document.getElementById("bom").innerHTML;
        let otimo = document.getElementById("otimo").innerHTML;
        console.log(pessimo, ruim, indiferente, bom, otimo)
    </script>


    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script>
        google.charts.load('current', { packages: ['corechart'] });
        function desenharGrafico() {
            var tabela = new google.visualization.DataTable();
            tabela.addColumn('string', 'avaliacao');
            tabela.addColumn('number', 'resultado');
            tabela.addRows(
                [
                    ['Péssimo', parseInt(pessimo)],
                    ['Ruim', parseInt(ruim)],
                    ['Indiferente', parseInt(indiferente)],
                    ['Bom', parseInt(bom)],
                    ['Ótimo', parseInt(otimo)]
                ]);

            var opcoes = {
                'title': 'Resultado Avaliação',
                'hight': 300,
                'width': 800,
                is3D: true,
                legend: 'labeled',
                pieSliceText: 'value',
                //colors: ['red', 'yellow', 'purple', 'blue', 'green']
                slices: {
                    0: { color: 'red' },
                    1: { color: 'grey' },
                    2: { color: 'purple' },
                    3: { color: 'blue' },
                    4: { offset: 0.2, color: 'green' },
                }
            };
            var grafico = new google.visualization.PieChart(document.getElementById('graficoPizza'));
            grafico.draw(tabela, opcoes);
        }

        google.charts.setOnLoadCallback(desenharGrafico);

    </script>

</head>
<body>
    <div id="graficoPizza"></div>
</body>
</html>

WebAppGraficosHighcharts/Views/Shared/Css/_bootstrap-select.cshtml
<link rel="stylesheet" type="text/css" href="~/lib/bootstrap-select-1.13.14/dist/css/bootstrap-select.css">
<link rel="stylesheet" type="text/css" href="~/css/Shared/select-picker-personalizacao.css" />

WebAppGraficosHighcharts/Views/Shared/Css/_datatables.cshtml
<link rel="stylesheet" type="text/css" href="~/lib/dataTables/datatables.min.css" />

WebAppGraficosHighcharts/Views/Shared/Script/_bootstrap-select.cshtml
<script type="text/javascript" src="~/lib/bootstrap-select-1.13.14/dist/js/bootstrap-select.js"></script>

WebAppGraficosHighcharts/Views/Shared/Script/_datatables.cshtml
<script type="text/javascript" src="~/lib/dataTables/pdfmake.min.js"></script>
<script type="text/javascript" src="~/lib/dataTables/vfs_fonts.js"></script>
<script type="text/javascript" src="~/lib/dataTables/datatables.min.js"></script>
<script type="text/javascript" src="~/lib/dataTables/configuracao-padrao-datatables.js"></script>
<script type="text/javascript" src="~/lib/dataTables/configuracao-padrao-datatables.min.js"></script>

WebAppGraficosHighcharts/Views/Shared/Script/_highCharts.cshtml
<script type="text/javascript" src="~/lib/highCharts/highcharts.js"></script>
<script type="text/javascript" src="~/lib/highCharts/modules/exporting.js"></script>

WebAppGraficosHighcharts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gráficos Highcharts</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    @RenderSection("Head", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gráficos Highcharts</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            Gráficos Highcharts - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>